apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: loki-ingress
  namespace: loki
spec:
  rules: 
  - host: loki.femn.com
    http:
      paths: 
      - backend:
          serviceName: loki
          servicePort: 3100
        path: /
