apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      kafka {
              enable_auto_commit => true
              auto_commit_interval_ms => "1000"
              bootstrap_servers => "kafka:9092"
              #topics => ["test-filebeat"]
              topics => ["filebeat-sidecar"]
              type => ["filebeat-sidecar"]
              codec => json
          }
    }

    output {
       stdout{ codec=>rubydebug}
       #if [fields][pod_namespace] =~ "logging" {
           #elasticsearch {
             #hosts => ["elasticsearch-logging:9200"]
             ##hosts => ["elasticsearch-logging-0.elasticsearch-logging:9200"]
             #index => "%{[fields][pod_namespace]}-s-%{+YYYY.MM.dd}"
          #}
       if [type] == "filebeat-sidecar" {
           elasticsearch {
             hosts => ["elasticsearch-logging:9200"]
             index => "filebeat-%{+YYYY.MM.dd}"
          }
       } else {
          elasticsearch {
             hosts => ["elasticsearch-logging:9200"]
             index => "other-index-%{+YYYY.MM.dd}"
          }
       }
    }
