---
apiVersion: v1
kind: Pod
metadata:
  name: csi-cephfs-demo-pod
  namespace: ceph
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/usr/share/busybox"
          name: ceph-active-pvc
  volumes:
    - name: ceph-active-pvc
      persistentVolumeClaim:
        claimName: csi-cephfs-pvc
        readOnly: false
