---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQC4eWdhtuCnGxAAmuNy7Ln58R4NzyagOddnYw==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQC4eWdhtuCnGxAAmuNy7Ln58R4NzyagOddnYw==
