apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/name: etcd
    name: etcd-monitor
    namespace: kube-system
  spec:
    ports:
    - name: https-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Endpoints
  metadata:
    labels:
      app.kubernetes.io/name: etcd
    name: etcd-monitor
    namespace: kube-system
  subsets:
  - addresses:
    - ip: 192.168.80.6
    - ip: 192.168.80.7
    - ip: 192.168.80.8
    ports:
    - name: https-metrics
      port: 2379
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
