apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka-exporter
    name: kafka-exporter
    namespace: monitoring
  spec:
    ports:
    - name: container-1-web-1
      port: 9308
      protocol: TCP
      targetPort: 9308
    selector:
      app: kafka-exporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 2
    labels:
      app: kafka-exporter
    name: kafka-exporter
    namespace: monitoring
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: kafka-exporter
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kafka-exporter
      spec:
        affinity: {}
        containers:
        - args:
          - --kafka.server=kafka-0.kafka-headless.logging:9092
          env:
          - name: TZ
            value: Asia/Shanghai
          - name: LANG
            value: C.UTF-8
          image: danielqsj/kafka-exporter:latest
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: kafka-exporter
          ports:
          - containerPort: 9308
            name: web
            protocol: TCP
          resources:
            limits:
              cpu: 287m
              memory: 287Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/zoneinfo/Asia/Shanghai
            name: tz-config
          - mountPath: /etc/localtime
            name: tz-config
          - mountPath: /etc/timezone
            name: timezone
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: ""
          name: tz-config
        - hostPath:
            path: /etc/timezone
            type: ""
          name: timezone
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
