apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: prom-ingress
      namespace: monitoring
    spec:
      rules:
        - host: alert.femn.com
          http:
            paths:
              - backend:
                  service:
                    name: alertmanager-main
                    port:
                      number: 9093
                path: /
                pathType: ImplementationSpecific
        - host: grafana.femn.com
          http:
            paths:
              - backend:
                  service:
                    name: grafana
                    port:
                      number: 3000
                path: /
                pathType: ImplementationSpecific
        - host: prom.femn.com
          http:
            paths:
              - backend:
                  service:
                    name: prometheus-k8s
                    port:
                      number: 9090
                path: /
                pathType: ImplementationSpecific
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
